openapi: 3.0.1
info:
  title: clients
  description: API Definition of clients
  version: 1.0.0
servers:
- url: http://localhost:8290/clients
paths:
  /:
    get:
      responses:
        default:
          description: Default response
