openapi: 3.0.1
info:
  title: orders
  description: API Definition of orders
  version: 1.0.0
servers:
- url: http://localhost:8290/orders
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /{order_id}:
    get:
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /{order_id}/status:
    put:
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
